name: Drone Buddy Mobile App

on:
  push:
    branches: [ master, build_ci ]
  pull_request:
    branches: [ master, build_ci ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build Apk
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'
          channel: 'stable'
      # This action sets up a java environment
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - uses: actions/upload-artifact@v2
        with:
          name: Debug APK Files
          path: build/app/outputs/apk/debug/*.apk
