name: Drone Buddy Mobile App

on:
  push:
    branches: [ master, build_ci ]
  pull_request:
    branches: [ master, build_ci ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build Apk
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build apk --release --split-per-abi
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      # - run: flutter build appbundle --debug
      # - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v2
        with:
          name: Debug APK Files
          path: build/app/outputs/apk/debug/*.apk
      - uses: actions/upload-artifact@v2
        with:
          name: Release APK Files
          path: build/app/outputs/apk/release/*.apk
